import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import LeftBar from "@/components/LeftBar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html className="min-h-screen" lang="en">
        <body
          className={
            inter.className +
            " " +
            "h-screen w-full  bg-[#1C1F2E]  text-slate-200 flex-col"
          }
        >
          <header>
            <div className="w-full bg-[#1C1F2E] fixed z-50 py-3 px-5 flex justify-between">
              <p>Zoom-clone</p> 
             <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
            </div>
          </header>
          <div className="flex min-h-full w-full">
            <LeftBar />
            <main className="pl-7 pr-7 pb-7 pt-14 bg-[#161925] min-h-full w-full">
              {children}
            </main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
